apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bfuk67iyi-dotnet-basic
  janus-idp.io/tekton: bfuk67iyi-dotnet-basic
  backstage.io/kubernetes-id: bfuk67iyi-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bfuk67iyi-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
